### ISSUE TITLE
Suggestion for `scram -j`

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/SCRAM#28]
Hi,
I would find it useful if `scram b -j` or `scram b -j0` would default to using as many jobs as there are (logical) cores on the machine.

Right now I'm using `scram b -j$(nproc)`, so it's not much of a problem, but it might be nice.

.Andrea

**Comment by Dr15Jones** [comment]
assign core

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/SCRAM/commit/47a8a6531741099b71a5561f18872218809eaf1c should provide this feature and it is already part of existing/default scram verson on cvmfs.
