### ISSUE TITLE
ProjectRename broken

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/SCRAM#32]
Several users have reported an issue using ProjectRename in the past week.

Here is a minimum example to reproduce the problem:
```
mkdir test
cd test
cmsrel CMSSW_10_3_0
cd CMSSW_10_3_0/src/
cmsenv
cd ../../
tar --exclude-caches-all --exclude-vcs -zcf ${CMSSW_VERSION}.tar.gz -C ${CMSSW_BASE}/.. ${CMSSW_VERSION}
rm -rf CMSSW_10_3_0
cd ..
mkdir test2
cd test2
tar -xzf ../test/CMSSW_10_3_0.tar.gz 
cd CMSSW_10_3_0
scram b ProjectRename
```

The output is:
```
Cannot parse "setup" - file /afs/cern.ch/user/p/pedrok/test/CMSSW_10_3_0/config/Self.xml not known
```

The example is reproducible on both lxplus and cmslpc at FNAL. It seems to be independent of the CMSSW release version.

**Comment by kpedro88** [comment]
@smuzaffar @mrodozov please take a look at this ASAP

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmsdist/pull/4473 should fix this. I will build and upload to the repo and will ask Bockjoo to install it. Once available under /cvmfs/cms.cern.ch then issue should be fixed for all existing releases.

**Comment by kpedro88** [comment]
@smuzaffar I want to make sure the fix will work properly. It looks like the code is changed so if it doesn't find the file `$self->{configdir}."/Self.xml"`, the `initpathvars()` function will just return. Is this function an important part of ProjectRename? It seems that exiting prematurely may not make ProjectRename work again...

The problem is that ProjectRename is looking in the *old* directory for `Self.xml` rather than the new directory.

**Comment by smuzaffar** [comment]
@kpedro88 , `initpathvars()` does not change the `ProjectRename` behaviour. New SCRAM is available for CMSSW_10_4_X_2018-11-02-2300 and above , please test this IB for ProjectRename and let me know if it still does not work.

**Comment by kpedro88** [comment]
@smuzaffar thanks, it appears to work now with the IB you specified.

**Comment by smuzaffar** [comment]
@kpedro88 , this is already available in /cvmfs/cms.cern.ch. Do you still issue with ProjectRename?

**Comment by kpedro88** [comment]
@smuzaffar for some reason the modified date didn't change, so I thought it wasn't updated, but it does appear to work correctly now.

**Comment by smuzaffar** [comment]
/cvmfs/cms.cern.ch/common/scram is wrapper script which should pick the latest SCRAM version (where actual fix was integrated).
