### ISSUE TITLE
Multiple options in USER_CXXFLAGS

### ISSUE THREAD

**Issue by schneiml** [cms-sw/SCRAM#33]
I am trying to pass options to the compiler via `USER_CXXFLAGS`, but it seems I can pass at most one option:

```
scram b USER_CXXFLAGS="-g"
...
>> Compiling edm plugin /tmp/schneiml/CMSSW_10_5_CLANG_X_2019-02-06-2300/src/CondTools/DQM/plugins/DQMReferenceHistogramRootFilePopConAnalyzer.cc 
```
(all good)

```
scram b USER_CXXFLAGS="-g -Os"
gmake: *** unknown output-sync type 's'.  Stop.
gmake: *** [There are compilation/build errors. Please see the detail log above.] Error 2
```
It looks like the additional options get passed to make instead of the compiler.

I am using `CMSSW_10_5_CLANG_X_2019-02-06-2300` and the options that I actually want to pass are a bit longer than what I used in the example: 
```
-Xclang -load -Xclang src/DQMServices/Components/scripts/dxr-index.so -Xclang -plugin -Xclang dxr-index -Xclang -plugin-arg-dxr-index -Xclang $PWD/src
```

I can work around the problem using sth. like this:
```
scram b -v USER_CXXFLAGS="-O2 CXXFLAGS='$OLD_ARGS $PLUGIN'"
```
but that seems like a very bad thing to do.

**Comment by smuzaffar** [comment]
please try this
- bash/sh:
  - USER_CXXFLAGS="-g -Os"  scram build
- csh/tcsh:
  - env USER_CXXFLAGS="-g -Os"  scram build

**Comment by schneiml** [comment]
I just tested it and passing the arguments as an environment variable works correctly. Thanks!
