### ISSUE TITLE
[v3][tests] Arguments mismatch when calling `MakeInterface.exec` in `tests/s_t_MakeInterface.py`

### ISSUE THREAD

**Issue by ShamrockLee** [cms-sw/SCRAM#52]
The argument signature of method `exec` of class `MakeInterface` is

```python
exec(self, args, opts)
```

but it is called in `s_t_MakeInterface.py` as

```python
a = MakeInterface()
a.exec("/tmp/makefile")
```

causing the test to fail.

**Comment by smuzaffar** [comment]
thanks for pointing this out. `s_t_MakeInterface.py` is obsolete so I have deleted that tests file.
