### ISSUE TITLE
Error message does not display properly

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/SCRAM#59]
I just encountered this error message: https://github.com/cms-sw/SCRAM/blob/39d67326880e1fd3197a3279e95853a63280dd58/SCRAM/Configuration/ConfigArea.py#L75-L81

It displays exactly as follows:
```
WARNING: In non-interactive mode release checks e.g. deprecated releases, production architectures are disabled.
ERROR: Can not setup your current working area for SCRAM_ARCH: $ENV{SCRAM_ARCH}
Your current development area ${location}/${areaname}
is using a different ${areaname}/config then the one used for
/cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_4_8
```

i.e. the environment variables are not evaluated. I think this was ported from perl and needs to be modified to get the environment variable values in Python.

**Comment by smuzaffar** [comment]
thanks @kpedro88 for reporting, https://github.com/cms-sw/SCRAM/pull/60 should fix this.
