### ISSUE TITLE
`import imp` is deprecation in Python 3.11 in favour of `importlib` and is removed in Python 3.12

### ISSUE THREAD

**Issue by ShamrockLee** [cms-sw/SCRAM#71]
When building SCRAMv3 with Python 3.12, setuptools complains about missing module `imp`:

```
       > Traceback (most recent call last):
       >   File "/build/source/nix_run_setup", line 8, in <module>
       >     exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
       >   File "setup.py", line 6, in <module>
       >     import imp
       > ModuleNotFoundError: No module named 'imp'
```

As the [official documentation of `imp`](https://docs.python.org/3.11/library/imp.html) and the [StackOverflow answer](https://stackoverflow.com/questions/77401730/modulenotfounderror-no-module-named-imp) point out, we need to migrate from `imp` to `importlib` to resolve this build failure.

**Comment by Dr15Jones** [comment]
Assign core
