### ISSUE TITLE
Executable name consistency

### ISSUE THREAD

**Issue by ShamrockLee** [cms-sw/SCRAM#74]
When building SCRAM v3 from the source, the executable name (CLI command name) specified in `setup.py` is `SCRAM`. However, it is `scram` in SCRAM v2 and on LXPLUS.

Is it a design choice to choose a different, all-capital command for SCRAM v3, or is it meant to be `scram`?

https://github.com/cms-sw/SCRAM/blob/662aa639caa52d0ccc931f0ed41f245ad37c9765/setup.py#L267-L270

**Comment by smuzaffar** [comment]
It should be `scram` and not `SCRAM`

**Comment by ShamrockLee** [comment]
Thank you for getting back to me so quickly! I'll send a pull request to correct it.

I'm trying to get the package build scripts included in [Nixpkgs](https://github.com/NixOS/nixpkgs) and considering the name to identify it. Since the name `scram` is [occupied](https://pypi.org/project/scram/) on PyPI, would `cms-scram` be a good choice?

**Comment by smuzaffar** [comment]
> would cms-scram be a good choice?

should be fine
